#!/usr/bin/env python3
"""
Agent 2: Asset Reviewer
=======================
Reviews assets generated by Agent 1 and validates completeness, accuracy, and quality.
Enhances descriptions and detects edge cases like duplicates or missing assets.

Flow:
1. Load assets from Agent 1 output
2. Review each asset for quality and completeness
3. Check for duplicates and missing assets
4. Enhance descriptions where needed
5. Human intervention: Confirm findings and suggested improvements
6. Save enhanced asset records
"""

from google import genai
import json
import os
from datetime import datetime
from typing import Dict, List, Optional, Any, Tuple

# Import Pydantic models from models.py
from backend.services.production.app.services.phase_1_agents.models import AssetReviewReport

# Import prompts from prompts.py
from backend.services.production.app.services.phase_1_agents.prompts import Agent2Prompts

import sys
from pathlib import Path

# Add backend to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))
from backend.shared.utils.logger import get_logger

# Initialize logger for this module
logger = get_logger(__name__)



class AssetReviewerAgent:
    """
    Agent 2: Reviews and enhances assets from Agent 1

    This agent performs comprehensive quality assurance on extracted assets,
    checking for completeness, duplicates, missing items, and description quality.
    """

    def __init__(self, api_key: str, model_name: str = "gemini-3.1-pro-preview"):
        """
        Initialize Asset Reviewer Agent

        Args:
            api_key: Google AI API key
            model_name: Gemini model to use
        """
        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name
        self.original_assets = {}
        self.review_results = {}
        self.enhanced_assets = {}
        self.human_feedback_log = []
        self.script_content = ""

    def load_agent1_output(self, agent1_output_path: str) -> None:
        """
        Load assets from Agent 1 output file

        Args:
            agent1_output_path: Path to Agent 1 JSON output
        """
        with open(agent1_output_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        self.original_assets = data.get('extracted_assets', {})
        self.script_content = ""  # Will be loaded separately if needed

        logger.info(f"✓ Loaded Agent 1 output from: {agent1_output_path}")
        logger.info(f"   Characters: {len(self.original_assets.get('characters', []))}")
        logger.info(f"   Locations: {len(self.original_assets.get('locations', []))}")
        logger.info(f"   Props: {len(self.original_assets.get('props', []))}")

    def load_script(self, script_path: str) -> None:
        """
        Load original script for reference during review

        Args:
            script_path: Path to script file
        """
        with open(script_path, 'r', encoding='utf-8') as f:
            self.script_content = f.read()

        logger.info(f"✓ Script loaded for reference ({len(self.script_content)} characters)")

    def _create_review_prompt(self) -> str:
        """Create comprehensive prompt for asset review using centralized prompts"""
        return Agent2Prompts.asset_review(self.script_content, self.original_assets)

    def review_assets(self) -> Dict[str, Any]:
        """
        Review assets using Gemini with structured output

        Returns:
            Dictionary containing comprehensive review results
        """
        if not self.original_assets:
            raise ValueError("No assets loaded. Call load_agent1_output() first.")

        prompt = self._create_review_prompt()

        try:
            # Use structured output with Pydantic schema
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config={
                    "response_mime_type": "application/json",
                    "response_schema": AssetReviewReport,
                }
            )

            # Get the parsed objects directly
            parsed_review: AssetReviewReport = response.parsed

            # Convert to dictionary for backward compatibility
            self.review_results = parsed_review.model_dump()

            quality = self.review_results.get('overall_quality_score', {})
            logger.info(f"✓ Review complete - Quality: {quality.get('completeness', 0)}/100")

            return self.review_results

        except Exception as e:
            logger.error(f"Review error: {e}")
            raise

    def _print_review_summary(self) -> None:
        """Print summary of review results"""

        logger.info("\n" + "─"*60)
        logger.info("REVIEW SUMMARY")
        logger.info("─"*60)

        # Quality scores
        quality = self.review_results.get('overall_quality_score', {})
        logger.info("\nQUALITY SCORES:")
        logger.info(f"   Completeness: {quality.get('completeness', 'N/A')}/100")
        logger.info(f"   Accuracy: {quality.get('accuracy', 'N/A')}/100")
        logger.info(f"   Detail Level: {quality.get('detail_level', 'N/A')}/100")
        logger.info(f"   Production Ready: {quality.get('production_readiness', 'N/A')}/100")

        # Missing assets
        completeness = self.review_results.get('completeness_check', {})
        missing_chars = len(completeness.get('missing_characters', []))
        missing_locs = len(completeness.get('missing_locations', []))
        missing_props = len(completeness.get('missing_props', []))

        if missing_chars or missing_locs or missing_props:
            logger.warning(f"\nMISSING ASSETS FOUND:")
            if missing_chars: print(f"   - {missing_chars} characters")
            if missing_locs: print(f"   - {missing_locs} locations")
            if missing_props: print(f"   - {missing_props} props")
        else:
            logger.info(f"\n✓ No missing assets detected")

        # Duplicates
        duplicates = self.review_results.get('duplicates_detected', {})
        dup_count = (len(duplicates.get('characters', [])) +
                     len(duplicates.get('locations', [])) +
                     len(duplicates.get('props', [])))

        if dup_count > 0:
            logger.warning(f"\n{dup_count} duplicate(s) detected")
        else:
            logger.info(f"\n✓ No duplicates detected")

        # Enhancements
        enhancements = self.review_results.get('description_enhancements', {})
        enhanced_count = (len(enhancements.get('characters', [])) +
                          len(enhancements.get('locations', [])) +
                          len(enhancements.get('props', [])))

        logger.info(f"\n✨ {enhanced_count} description enhancement(s) suggested")

        # Issues
        issues = self.review_results.get('accuracy_issues', [])
        if issues:
            logger.warning(f"\n{len(issues)} accuracy issue(s) found")
        else:
            logger.info(f"\n✓ No accuracy issues found")

        # Edge cases
        edge_cases = self.review_results.get('edge_cases', [])
        if edge_cases:
            logger.info(f"\n📌 {len(edge_cases)} edge case(s) identified")

    def display_detailed_review(self) -> None:
        """Display detailed review results for human evaluation"""

        logger.info("\n" + "="*60)
        logger.info("DETAILED REVIEW RESULTS - HUMAN EVALUATION REQUIRED")
        logger.info("="*60)

        # Missing Assets
        completeness = self.review_results.get('completeness_check', {})

        if completeness.get('missing_characters'):
            logger.info("\n" + "─"*60)
            logger.warning("MISSING CHARACTERS:")
            logger.info("─"*60)
            for item in completeness['missing_characters']:
                logger.info(f"\n• {item.get('name', 'Unknown')}")
                logger.info(f"  Reason: {item.get('reason', 'N/A')}")

        if completeness.get('missing_locations'):
            logger.info("\n" + "─"*60)
            logger.warning("MISSING LOCATIONS:")
            logger.info("─"*60)
            for item in completeness['missing_locations']:
                logger.info(f"\n• {item.get('name', 'Unknown')}")
                logger.info(f"  Reason: {item.get('reason', 'N/A')}")

        if completeness.get('missing_props'):
            logger.info("\n" + "─"*60)
            logger.warning("MISSING PROPS:")
            logger.info("─"*60)
            for item in completeness['missing_props']:
                logger.info(f"\n• {item.get('name', 'Unknown')}")
                logger.info(f"  Reason: {item.get('reason', 'N/A')}")

        # Duplicates
        duplicates = self.review_results.get('duplicates_detected', {})

        for asset_type in ['characters', 'locations', 'props']:
            if duplicates.get(asset_type):
                logger.info(f"\n" + "─"*60)
                logger.info(f"DUPLICATE {asset_type.upper()}:")
                logger.info("─"*60)
                for dup in duplicates[asset_type]:
                    logger.info(f"\n• Duplicates: {', '.join(dup.get('duplicate_names', []))}")
                    logger.info(f"  Reason: {dup.get('reason', 'N/A')}")

        # Description Enhancements
        enhancements = self.review_results.get('description_enhancements', {})

        if enhancements.get('characters'):
            logger.info("\n" + "─"*60)
            logger.info("✨ CHARACTER DESCRIPTION ENHANCEMENTS:")
            logger.info("─"*60)
            for data in enhancements['characters']:
                logger.info(f"\n• {data.get('asset_name', 'Unknown')}")
                logger.info(f"  Original: {data.get('original_description', 'N/A')[:100]}...")
                logger.info(f"  Enhanced: {data.get('enhanced_description', 'N/A')[:100]}...")
                logger.info(f"  Improvements: {', '.join(data.get('improvements_made', []))}")

        if enhancements.get('locations'):
            logger.info("\n" + "─"*60)
            logger.info("✨ LOCATION DESCRIPTION ENHANCEMENTS:")
            logger.info("─"*60)
            for data in enhancements['locations']:
                logger.info(f"\n• {data.get('asset_name', 'Unknown')}")
                logger.info(f"  Original: {data.get('original_description', 'N/A')[:100]}...")
                logger.info(f"  Enhanced: {data.get('enhanced_description', 'N/A')[:100]}...")
                logger.info(f"  Improvements: {', '.join(data.get('improvements_made', []))}")

        if enhancements.get('props'):
            logger.info("\n" + "─"*60)
            logger.info("✨ PROP DESCRIPTION ENHANCEMENTS:")
            logger.info("─"*60)
            for data in enhancements['props']:
                logger.info(f"\n• {data.get('asset_name', 'Unknown')}")
                logger.info(f"  Original: {data.get('original_description', 'N/A')[:100]}...")
                logger.info(f"  Enhanced: {data.get('enhanced_description', 'N/A')[:100]}...")
                logger.info(f"  Improvements: {', '.join(data.get('improvements_made', []))}")

        # Accuracy Issues
        issues = self.review_results.get('accuracy_issues', [])
        if issues:
            logger.info("\n" + "─"*60)
            logger.warning("ACCURACY ISSUES:")
            logger.info("─"*60)
            for issue in issues:
                logger.info(f"\n• {issue.get('asset_name', 'Unknown')} ({issue.get('asset_type', 'N/A')})")
                logger.info(f"  Issue: {issue.get('issue', 'N/A')}")
                logger.info(f"  Fix: {issue.get('suggested_fix', 'N/A')}")

        # Edge Cases
        edge_cases = self.review_results.get('edge_cases', [])
        if edge_cases:
            logger.info("\n" + "─"*60)
            logger.info("📌 EDGE CASES:")
            logger.info("─"*60)
            for case in edge_cases:
                logger.info(f"\n• {case.get('asset_name', 'Unknown')} - {case.get('case_type', 'N/A')}")
                logger.info(f"  Description: {case.get('description', 'N/A')}")
                logger.info(f"  Recommendation: {case.get('recommendation', 'N/A')}")

        # Recommendations
        recommendations = self.review_results.get('recommendations', [])
        if recommendations:
            logger.info("\n" + "─"*60)
            logger.info("💡 RECOMMENDATIONS:")
            logger.info("─"*60)
            for i, rec in enumerate(recommendations, 1):
                logger.info(f"{i}. {rec}")

        logger.info("\n" + "="*60)

    def request_human_feedback(self) -> Dict[str, Any]:
        """
        Request human feedback on review findings

        Returns:
            Dictionary containing feedback request info
        """
        logger.info("\n" + "🤔 "*30)
        logger.info("HUMAN INTERVENTION CHECKPOINT - AGENT 2")
        logger.info("🤔 "*30)

        logger.info("\nPlease review the findings above and provide feedback:")
        logger.info("\nEXPECTED FEEDBACK FORMAT:")
        print("""
{
    "approve_enhancements": true/false,
    "approve_missing_additions": {
        "characters": ["name1", "name2"],  // Which missing to add
        "locations": ["name1"],
        "props": []
    },
    "approve_duplicate_merges": {
        "characters": ["merge_id1"],  // Which duplicates to merge
        "locations": [],
        "props": []
    },
    "custom_modifications": {
        "CHARACTER_NAME": {
            "description": "Custom enhanced description",
            "key_features": ["custom feature"]
        }
    },
    "reject_findings": {
        "missing_assets": ["asset_name"],  // Assets reviewer suggested but shouldn't add
        "enhancements": ["asset_name"]     // Assets that don't need enhancement
    },
    "additional_notes": "Any additional human observations"
}
        """)

        logger.info("\n" + "="*60)
        logger.info("⏸AGENT PAUSED - Waiting for human feedback...")
        logger.info("="*60)

        return {
            "feedback_type": "pending",
            "message": "Human feedback required before applying enhancements"
        }

    def apply_enhancements(self, human_feedback: Optional[Dict[str, Any]] = None) -> None:
        """
        Apply approved enhancements to create final enhanced assets

        Args:
            human_feedback: Optional human feedback to guide enhancement application
        """
        # Start with original assets
        self.enhanced_assets = json.loads(json.dumps(self.original_assets))

        # Log feedback
        if human_feedback:
            self.human_feedback_log.append({
                "timestamp": datetime.now().isoformat(),
                "agent": "Agent 2: Asset Reviewer",
                "feedback": human_feedback
            })

        # Apply description enhancements
        enhancements = self.review_results.get('description_enhancements', {})
        enhanced_count = 0

        for asset_type in ['characters', 'locations', 'props']:
            enhancement_list = enhancements.get(asset_type, [])
            if enhancement_list:
                for enhancement_data in enhancement_list:
                    asset_name = enhancement_data.get('asset_name')
                    # Find the asset in enhanced_assets
                    for asset in self.enhanced_assets.get(asset_type, []):
                        if asset.get('name') == asset_name:
                            # Apply enhanced description
                            asset['description'] = enhancement_data.get('enhanced_description',
                                                                        asset.get('description'))
                            enhanced_count += 1

        # Add missing assets if approved
        added_count = 0
        if human_feedback and human_feedback.get('approve_missing_additions'):
            completeness = self.review_results.get('completeness_check', {})

            for asset_type in ['characters', 'locations', 'props']:
                approved_names = human_feedback['approve_missing_additions'].get(asset_type, [])
                missing_items = completeness.get(f'missing_{asset_type}', [])

                for item in missing_items:
                    if item.get('name') in approved_names:
                        # Create basic asset from missing asset data
                        # Preserve ID from MissingAsset model or generate new one
                        basic_asset = {
                            'id': item.get('id'),  # ID already generated by MissingAsset Pydantic model
                            'name': item.get('name'),
                            'description': item.get('description'),
                            'importance': item.get('importance', 'background')
                        }
                        self.enhanced_assets[asset_type].append(basic_asset)
                        added_count += 1

        # Apply custom modifications from human
        if human_feedback and human_feedback.get('custom_modifications'):
            for asset_name, modifications in human_feedback['custom_modifications'].items():
                # Find and update the asset
                for asset_type in ['characters', 'locations', 'props']:
                    for asset in self.enhanced_assets.get(asset_type, []):
                        if asset.get('name') == asset_name:
                            asset.update(modifications)

        logger.info(f"✓ Enhanced {enhanced_count} descriptions, added {added_count} missing assets")

    def run_full_pipeline(self, agent1_output_path: str, script_path: str) -> Dict[str, Any]:
        """
        Run the complete Agent 2 pipeline

        Args:
            agent1_output_path: Path to Agent 1 output JSON
            script_path: Path to original script

        Returns:
            Dictionary with review results and enhanced assets
        """
        # Step 1: Load Agent 1 output and script
        self.load_agent1_output(agent1_output_path)
        self.load_script(script_path)

        # Step 2: Review assets
        self.review_assets()

        # Step 3: Display detailed review
        self.display_detailed_review()

        # Step 4: Request human feedback
        feedback_info = self.request_human_feedback()

        return {
            "status": "pending_human_review",
            "review_results": self.review_results,
            "feedback_request": feedback_info,
            "next_step": "Provide human feedback via apply_enhancements() method"
        }


def main():
    """Example usage of Agent 2"""

    # Initialize agent
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY/GOOGLE_API_KEY environment variable not set")
    agent = AssetReviewerAgent(api_key=api_key)

    # Note: In real usage, you would pass actual Agent 1 output path
    logger.info("Agent 2: Asset Reviewer initialized")
    logger.info("Use run_full_pipeline() with Agent 1 output and script paths")


if __name__ == "__main__":
    main()
